---
title: "Sensory and neural mechanisms of parent-offspring recognition in a maternal mouthbrooding African cichlid fish"
author: "Emily Ray^1^*"
date: '`r format(Sys.time())`'
output:
  bookdown::pdf_document2:
    includes:
      before_body:
      in_header: 
    keep_tex: yes
    latex_engine: xelatex
    number_sections: no
    toc: no
  bookdown::html_document2:
    number_sections: no
    theme: readable
    toc: yes
  bookdown::tufte_html2:
    number_sections: no
    toc: yes
  bookdown::word_document2:
    toc: no
    reference_docx: template/nature_style.docx
    number_sections: no
fontsize: 12pt
linestretch: 1.5
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/ecology.csl
bibliography: ref.bib
always_allow_html: yes
links-as-notes: true
notes-after-punctuation: false
---


\footnotesize 

^1^Department of Biological Sciences, Louisiana State University, Baton Rouge, LA, USA  

\* **Corresponding author**, email: eray8@lsu.edu; 349 Life Science Building, Baton Rouge, LA 70803

\normalsize

**Running headline**: Cichlid offspring recognition

**Abstract**: Parental care evolved independently several times and is present in diverse taxa, from insects to mammals. Recognizing offspring is important for parental care - parents must identify and locate their young to provide resources and protection. Despite the importance of offspring recognition to species persistence, little is known about the sensory and neural mechanisms that underlie recognition in fishes, the oldest and largest group of vertebrates. Here, we identify the sensory and neural mechanisms of offspring recognition in a maternal, mouthbrooding African cichlid fish, *Astatotilapia burtoni*. Preliminary behavioral data suggests visual information is necessary for *A. burtoni* offspring recognition, and we identify several brain regions implicated in offspring recognition. Understanding the mechanisms underlying offspring recognition in a model fish species provides insight to the evolution of parental care across vertebrate taxa, and to cichlids response to changing environmental conditions, such as increased turbidity, that may impact their ability to send and receive sensory signals. 

\clearpage

# Introduction

Parental care has arisen from several independent evolutionary events and is present across taxa [@RN1, @RN2]. Parent-offspring recognition is critical for the maitenance of parental care because it allows parents to direct their care behaviors and energy allocation towards their own offspring, resulting in increased offspring success. Across vertebrates, parents and young rely on diverse signaling modalities for identification, including acoustic recognition in cows, chemosensory recognition in zebra finch hatchlings, and visual recognition in chimpanzees [@RN3, @RN4, @RN5]. Recognition can also be multimodal, and can involve redundant ("same message") or non-redundant ("different message") signals [@RN6]. In some species, both parents and offspring recognize each other (bi-directional recognition), while in others, either the offspring or the parent recognizes each other (uni-directional recognition) [@RN7, @RN8]. In fishes, both chemosensory and visual information can be important for parent-offspring recognition, and the sensory signals used vary between species [@RN9, @RN10]. Despite the importance of offspring recognition, how fishes, the oldest and most diverse group of vertebrates, perform this task is largely unknown.

Mouthbrooding is a form of parental care prsent in 53 genera of teleost fishes and 1 frog species [@RN11, @RN12]. Mouthbrooding parents hold their developing young in their mouths and typically cease feeding behavior, starving themselves while their offspring develop [@RN11]. Despite this starvation, filial cannibalism is not common during the mouthbrooding period [@RN13]. The maternal mouthbrooding African cichlid fish *Astatotilapia burtoni* is an emerging model for neurobiology and animal behavior research that is particulary well-suited for studying parent-offspring recognition [@RN14]. Female *A. burtoni* brood developing young in their mouths for ~14 days, then provide post-release maternal care by collecting fry in their mouths to protect their fry from threats [@RN15]. Adult *A. burtoni* cannibalize fry, thus parent-offspring recognition becomes critical, both so that mothers avoid maladaptively canniablizing their own offspring, and so that fry avoid swimming toward the wrong mouth and being consumed. However, despite the importance of parent-offspring recognition during the *A. burtoni* post release maternal care phase, which sensory signals and brain regions are important for this behavior are unknown.

In the cichlid fish *Pelvicachromis pulcher*, visual stimuli from fry are necessary for the maintenance of maternal care, while chemosensory stimuli from fry are not sufficient to maintain parental behaviors [@RN28]. However, the midas cichlid, *Cichlasoma citrinellum* relies on chemosensory information for parent-offspring recognition [@RN29], highlighting the diverse sensory mechanisms underlying parent-offspring recognition in cichlid fishes. During the *A. burtoni* post release maternal care phase, fry will attempt to enter the mouth of an adult male fish if provided only visual stimuli [@RN15], suggesting chemosensory information is necessary and non-redundant with visual information during *A. burtoni* parent-offspring recognition. 

The goal of this study was to determine the relative importance of visual and chemosensory signals during *A. burtoni* parent-offspring recognition, and identify brain regions and networks that are important for this behavior. We compared behavior in response to different fry stimuli and identified distinct activation patterns associated with parent-offspring recognition. Because fish are the largest and oldest vertebrate group, these findings have important implications for the evolution of parental care circuits and behavior across vertebrate taxa. 

# Methods

**Animal Care**  
*Astatotilapia burtoni* derived from a wild-caught stock from Lake Tanganyka, Africa were laboratory raised under conditions similar to their natural environment. (~28 °C, pH 8.0, 12-h light/12-h dark cycle). Fish were fed cichlid flakes (AquaDine, Healdsburg, CA, USA) daily and brine shrimp (Sally's Frozen Brine Shrimp, San Francisco, CA, USA) twice weekly. Prior to experiments, fish were housed in mixed sex groups in aquaria with gravel, halved terracotta pots to serve as shelters, and several dominant males. All experimental protocols were approved by the Institutional Animal Care and Use Committee (IACUC) at Louisiana State University, Baton Rouge, LA, and were in accordance with the guidelines set by the National Institutes of Health (NIH) Guide for the Care and Use of Laboratory Animals, 2011.

**Experimental Procedures**  
To determine the relative importance of visual and chemosensory signals in *A. burtoni* offspring recognition, we compared the behavior of mouthbrooding females on the day of fry release when exposed to either 1) only visual 2)only chemosensory 3) both visual and chemosensory or 4) no stimuli from their fry (N = 5 per condition). To obtain chemosensory stimuli, 12 fry were soaked in 250 mL of reverse osmosis filtered water for 3 hours. The fry were then removed from the water, and the water was delivered to the focal female at the start of the behavior trial via a gravity fed system with a flow rate of 3.47 mL s^-1. Visual stimuli was the focal female's fry, visible through a clear, acrylic barrier. Behavior trials were recorded for 30 minutes and behavior was quantified using ToxTrac animal tracking software (@RN16). 

Immediately following behavior trials, the focal female's standard length (SL) and body mass (BM) were recorded. Females were sacrificed via rapid cervical transections. Ovaries were removed and weighted to calculate gonadosomatic index (GSI). Brains were exposed and heads were fixed in 4% paraformaldehyde at 4°C for 24 h. Heads were then transferred to 1x phosphate buffered saline (PBS) and rinsed for ~ 24 h at 4°C. Brains were cryoprotected in 30% sucrose made in 1x PBS for 24 h at 4°C, embedded in optimal cutting temperature (OCT) media and sectioned in the transverse plane at 20 µm using a cryostat (Cryostar NX50), then collected on alternate sets of charged slides (VWR, Superfrost) and stored at -80°C until staining. 

**pS6 Immunohistochemistry**  
 To identify activated neurons, immunohistochemistry for the phosphorylated ribosome protein pS6 was performed, as used previously (@RN24, @RN18). Phosphorlyation of S6 is associated with increased translation, and pS6 is present in neurons that were activated within ~1 h prior to sacrifice (@RN27, @RN25). Slides were thawed, and sectioned tissue was surrounded with a hydrophobic barrier (Immedge Pen, Vector Laboratories). Slides were washed with 1xPBS (3 x 10 min), and non-specific binding was blocked (2% bovine serum albumin, 0.3% Triton-X, and 5.0% normal goat serum, made in 1 x PBS, 2 h). Slides were incuated with pS6 antibody (1:1500; Cell Signaling Technologies pS6 ribosomal protein S235/236 antibody #4858) overnight at 4°C. Slides were rinsed with 1xPBS (3 x 10 min), incubated with biotinylated goat anti-rabbit IgG secondary antibody (Vector Labs BA-1000; 1:277) at room temperature for 2 h, and reacted with 3,3’-diaminobenzidine (DAB, DAB Substrate Kit, Peroxidase (HRP), with Nickel Vector Laboratories SK-4100) substrate for 30 mins. Slides were rinsed in DI water (10 min) to stop the DAB reaction, then dehydrated in an ethanol series (50%, 70%, and 95% EtoH 1 min, 100% EtoH 2 x 2 min), cleared in xylene (2 x 3 min), and coverslipped with cytoseal-60 (Epredia).

**Imaging and Analysis**  
Slide were visualized on a Nikon Eclipse Ni microscope and images were taken using a digital color camera (Nikon DS-Fi2) controlled with Nikon NIS elements software. Quantification of pS6 stained cells was performed by individuals blind to the experimental condition. Borders were drawn around regions of interest (ROI) and gridlines were applied. Boxes were randomly selected (3-5 depending on ROI size) and the number of pS6 stained cells within selected boxes was counted. pS6 stained cell density was calculated as the number of pS6 stained cells divided by the area of the boxes that were quantified. For a given region, 3-4 consecutive sections were quantified at the same location within the nucleus across animals. Data from each animal was averaged together to calculate a mean density of pS6 stained cells in each brain region. 

We quantified 3 brain nuclei that are implicated in maternal care and social behavior: subdivisions 4 and 5 of the central dorsal telencephalon (Dc-4, Dc-5) and the periventricular posterior tuberculum (TPp).

**Statistical Analysis**   
All analysis was performed in R 4.1.0 (REF).

## Results

## Discussion

# References
